# Generated by Django 5.1.4 on 2024-12-05 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, choices=[('_', '_'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('3a+', '3А+'), ('3b+', '3Б+')], max_length=3, null=True)),
                ('summer', models.CharField(blank=True, choices=[('_', '_'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('3a+', '3А+'), ('3b+', '3Б+')], max_length=3, null=True)),
                ('autumn', models.CharField(blank=True, choices=[('_', '_'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('3a+', '3А+'), ('3b+', '3Б+')], max_length=3, null=True)),
                ('spring', models.CharField(blank=True, choices=[('_', '_'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('3a+', '3А+'), ('3b+', '3Б+')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('fam', models.TextField(max_length=20)),
                ('name', models.TextField(max_length=20)),
                ('otc', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Passages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('beauty_title', models.TextField(blank=True, null=True)),
                ('other_title', models.CharField(blank=True, max_length=100, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('connect', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'новая'), ('pending', 'в работе'), ('accepted', 'принято'), ('rejected', 'отклонено')], default='new', max_length=10)),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passage.coordinates')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passage.levels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passage.user')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField(blank=True, null=True)),
                ('title', models.TextField(blank=True, max_length=255, null=True)),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passage.passages')),
            ],
        ),
    ]
