# Generated by Django 5.1.4 on 2024-12-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
